
const setEventAttr = function ($target, propName, value) {
    if ($target && propName && value) {

        const eventPropertyArray = [
            'onabort',
            'onafterprint',
            'onbeforeprint',
            'onbeforeunload',
            'onblur',
            'oncanplay',
            'oncanplaythrough',
            'onchange',
            'onclick',
            'oncontextmenu',
            'oncopy',
            'oncut',
            'ondblclick',
            'ondrag',
            'ondragend',
            'ondragenter',
            'ondragleave',
            'ondragover',
            'ondragstart',
            'ondrop',
            'ondurationchange',
            'onended',
            'onerror',
            'onfocus',
            'onfocusin',
            'onfocusout',
            'onfullscreenchange',
            'onfullscreenerror',
            'onhashchange',
            'oninput',
            'oninvalid',
            'onkeydown',
            'onkeypress',
            'onkeyup',
            'onload',
            'onloadeddata',
            'onloadedmetadata',
            'onloadstart',
            'onmessage',
            'onmousedown',
            'onmouseenter',
            'onmouseleave',
            'onmousemove',
            'onmouseover',
            'onmouseout',
            'onmouseup',
            'onoffline',
            'ononline',
            'onopen',
            'onpagehide',
            'onpageshow',
            'onpaste',
            'onpause',
            'onplay',
            'onplaying',
            'onprogress',
            'onratechange',
            'onresize',
            'onreset',
            'onscroll',
            'onsearch',
            'onseeked',
            'onseeking',
            'onselect',
            'onshow',
            'onstalled',
            'onsubmit',
            'onsuspend',
            'ontimeupdate',
            'ontoggle',
            'ontouchcancel',
            'ontouchend',
            'ontouchmove',
            'ontouchstart',
            'ontransitionend',
            'onunload',
            'onvolumechange',
            'onwaiting',
            'onwheel',
        ]
        

        if (propName) {

        }

    }
}